In [2]:
import numpy as np
from torch.utils.data import Dataset, DataLoader

class RandomDataset(Dataset):
    def __getitem__(self, index):
        return np.random.randint(0, 1000, 3)

    def __len__(self):
        return 16
    
dataset = RandomDataset()
dataloader = DataLoader(dataset, batch_size=2, num_workers=4)
for batch in dataloader:
    print(batch)

/om2/user/imgriff/conda_envs/torch_11_cuda_11/lib/python3.9/site-packages/torch/utils/data/dataloader.py:487: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(


tensor([[555, 541, 424],
        [938, 137, 986]])
tensor([[422,  23, 120],
        [780, 724, 971]])
tensor([[472, 394, 856],
        [491, 196, 628]])
tensor([[769, 541, 810],
        [790, 923, 613]])
tensor([[192, 852, 970],
        [ 77, 672, 407]])
tensor([[961, 752, 153],
        [890, 444, 101]])
tensor([[823, 981, 763],
        [132, 900, 619]])
tensor([[ 55, 626, 356],
        [556, 244, 312]])


In [ ]:
# above seems ok


In [4]:
# This looks good too! Output is data ixs, np random sequence, python random sequence

import torch
from torch.utils.data import DataLoader, Dataset
import numpy as np
import random

class RandomDataset(Dataset):
    def __getitem__(self, ind):
        return ind, np.random.randint(1, 10000), random.randint(1, 10000)

    def __len__(self):
        return 24

dl = DataLoader(RandomDataset(), batch_size=4, shuffle=False, num_workers=6)

epochs = 2
for _ in range(epochs):
    for batch in dl:
        print(batch)
    print("====" * 10)

[tensor([0, 1, 2, 3]), tensor([5233, 7934,  839, 4317]), tensor([7854, 3013, 5210, 7433])]
[tensor([4, 5, 6, 7]), tensor([9317, 1072, 7476, 6119]), tensor([1444,  142, 1742, 5730])]
[tensor([ 8,  9, 10, 11]), tensor([1779, 3468, 8078, 2485]), tensor([  86,  880,  964, 5175])]
[tensor([12, 13, 14, 15]), tensor([2600, 1143, 6184, 5446]), tensor([2036, 4006, 1739, 4187])]
[tensor([16, 17, 18, 19]), tensor([1563, 5870, 5665, 6710]), tensor([2719, 4475, 7793, 6425])]
[tensor([20, 21, 22, 23]), tensor([9220, 2582, 2015, 6193]), tensor([6225,  946,   47, 4969])]
[tensor([0, 1, 2, 3]), tensor([ 547, 5417, 6638, 4037]), tensor([1976, 1864, 5670,  229])]
[tensor([4, 5, 6, 7]), tensor([4301, 1531, 8096, 1755]), tensor([9172,  253,  127, 4418])]
[tensor([ 8,  9, 10, 11]), tensor([7865, 8112, 8066, 8569]), tensor([5933, 4826, 1229, 6105])]
[tensor([12, 13, 14, 15]), tensor([2027,  786, 3461, 1728]), tensor([2902, 9967, 5521, 2230])]
[tensor([16, 17, 18, 19]), tensor([8321, 6282, 5977, 6836]), tenso

In [5]:
torch.__version__

'1.11.0'

In [6]:
np.__version__

'1.22.3'