In [14]:
import h5py 
import numpy as np

In [54]:
with h5py.File("dummy_file2.h5", 'a') as f:
    for letter in "a":
        # check if letter is already in file
        if letter not in f.keys():
            f.create_dataset(f"{letter}/target", (10, 5), dtype="float32")
            f.create_dataset(f"{letter}/background", (10, 5), dtype="float32")

    for i in range(10):
        f["a"]['target'][i] = np.ones(5) * i 
        f["a"]['background'][i] = np.ones(5) * 3 * i
    

In [52]:
h5 = h5py.File("dummy_file2.h5", 'r')
print(h5.keys())
print(h5['a']['target'][:])
print(h5['a']['background'][:])
h5.close()

<KeysViewHDF5 ['a']>
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9.]]
[[ 0.  0.  0.  0.  0.]
 [ 3.  3.  3.  3.  3.]
 [ 6.  6.  6.  6.  6.]
 [ 9.  9.  9.  9.  9.]
 [12. 12. 12. 12. 12.]
 [15. 15. 15. 15. 15.]
 [18. 18. 18. 18. 18.]
 [21. 21. 21. 21. 21.]
 [24. 24. 24. 24. 24.]
 [27. 27. 27. 27. 27.]]


In [53]:
h5.close()