In [1]:
import h5py
import numpy as np
import os
from IPython import display
from pathlib import Path
from corpus.binaural_attention_h5 import BinauralAttentionDataset
import yaml


In [2]:
#### Config path 
cfg_path = "config/binaural_attn/word_task_half_co_loc_v08_gender_bal_4M_w_no_cue.yaml"
config = yaml.safe_load(open(cfg_path, 'r'))
corpus_config = config['corpus']
corpus_config

{'name': 'spatialized_commonvoice_audioset_scenes',
 'cue_type': 'mixed',
 'task': 'word',
 'root': '/om/scratch/Sun/imgriff/datasets/spatial_audio_pipeline/assets/dataset_binaural_attn/v08',
 'mixture_percentages': {'voice_only': 0.5, 'voice_and_location': 0.5},
 'gender_balanced_4M': True,
 'cue_free_percentage': 0.1,
 'v06': True}

In [7]:
dataset = BinauralAttentionDataset(**corpus_config, batch_size=10)

Using v06 dataset
/om/scratch/Sun/imgriff/datasets/spatial_audio_pipeline/assets/dataset_binaural_attn/v08
Using 0.1 cue free data
Using gender balanced training 4M set
cue type: mixed
mixture_percentages={'voice_only': 0.5, 'voice_and_location': 0.5}
913 files in train concat dataset
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4

In [10]:
cue, target, bg, label = dataset[100]

[9]


In [13]:
cue[9], bg[9]

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [14]:
target[9]

array([[ 2.5545494e-04,  2.0975040e-04,  1.6449876e-04, ...,
         1.6892853e-05, -5.5245124e-04, -1.1010909e-03],
       [ 1.3599879e-04,  2.1810611e-04,  4.0049959e-04, ...,
        -3.5504391e-03, -3.1160549e-03, -2.3812698e-03]], dtype=float32)